name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5 # Pin to your Terraform version

      # Step 3 - Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # change if needed

      # Step 4 - Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5 - Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 6 - Terraform Plan
      - name: Terraform Plan
        run: terraform plan 

      